"use server";
import { db, storage } from "@/Firebase/firebase";
import { ref, uploadBytes } from "firebase/storage";
import { revalidatePath } from "next/cache";
import {
  collection,
  getDocs,
  where,
  query,
  setDoc,
  doc,
  increment,
  updateDoc,
  getDoc,
} from "firebase/firestore";
const { ulid } = require("ulid");

const addNewMaterialToDb = async ({
  isFixed,
  name,
  vendor,
  rate,
  category,
  description,
  specs,
  orderedAs,
  image,
  cover,
  displayCover,
  usage,
}) => {
  try {
    // Checking if the material with the same name already exists
    const materialsCollectionRef = collection(db, "MATERIALS");
    const queryResult = query(
      materialsCollectionRef,
      where("name", "==", name),
    );
    const querySnapshot = getDocs(queryResult);
    if (!querySnapshot.empty) {
      return {
        type: "ERROR",
        message: "Material with this name already exists.",
      };
    }
    // Uploading the image and cover image to the storage using the id generated by ulid
    const id = ulid();
    const imageRef = ref(storage, `MATERIALS/${id}/image`);
    uploadBytes(imageRef, image.get("image"));
    const coverRef = ref(storage, `MATERIALS/${id}/cover`);
    uploadBytes(coverRef, cover.get("cover"));

    // Adding the material to the database
    const newDocRef = doc(materialsCollectionRef, id);
    setDoc(newDocRef, {
      isFixed,
      name,
      vendor,
      rate,
      category,
      description,
      specs,
      orderedAs,
      displayCover,
      usage,
    });

    // If the material is fixed, then check if there is any other material fixed in the same category and update it
    const categoriesCollectionRef = collection(db, "MATERIAL_CATEGORIES");
    const categoryDocRef = doc(categoriesCollectionRef, category);
    const categoryDoc = getDoc(categoryDocRef);
    if (isFixed) {
      const fixedMaterialOfCategory = categoryDoc.data().fixedMaterial;
      if (fixedMaterialOfCategory) {
        updateDoc(doc(materialsCollectionRef, fixedMaterialOfCategory), {
          isFixed: false,
        });
      }
    }

    // Updating the category usage and fixedMaterial
    updateDoc(categoryDocRef, {
      usage: increment(1),
      fixedMaterial: isFixed ? id : categoryDoc.data().fixedMaterial,
    });
    revalidatePath("/admin/materials", "page");
    return {
      type: "SUCCESS",
      message: "Material added successfully!",
    };
  } catch (error) {
    console.error("Error adding the material: " + error);
    return {
      type: "ERROR",
      message: "Something went wrong, please try again later.",
    };
  }
};

export default addNewMaterialToDb;
